---
language: "python"
python: "3.7"
dist: disco
sudo: required

pre-install:
  - sudo apt update
  - sudo apt upgrade -y

install:
  - sudo pip install ansible

script:
  - sudo ansible-playbook -i inventory setup.yml
