---
sudo: required

env:
   - distribution: ubuntu
     version: disco

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/root/desktop-setup:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /root/desktop-setup/setup.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 /root/desktop-setup/setup_ubuntu.sh'
